name: learning
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: 4.2.0+1
  audioplayers: ^0.20.1
  video_player: ^2.8.1
  animated_text_kit: ^4.2.1
  flutter_map: ^0.13.1
  latlong2: ^0.8.0
  photo_view: ^0.12.0
  circular_profile_avatar: ^2.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/temp/
    - assets/temp/alongwith.mp3
    - assets/temp/inthissession.mp3
    - assets/temp/MatrixScene.mp4
    - assets/temp/rowsandcolumns.mp3
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
          weight: 900
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Thin.ttf
          weight: 100
